# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   phoenix:
      # The image we're going to use.
      image: imluky/backend:latest
      env_file: ./backend/.env
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: ./backend
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - "4000:4000" #this will make you able to curl, from your windows host, to localhost:4000
      depends_on:
         # The DB container needs to be started before we start this container.
         - db
   db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      env_file: .env
      restart: always
      volumes:
         - pgdata:/var/lib/postgresql/data
   frontend:
      image: imluky/frontend:latest
      env_file: ./frontend/.env
      build:
         context: ./frontend
         dockerfile: Dockerfile
      ports:
         - "80:80"
      volumes:
         - ./frontend:/app
      
volumes:
   pgdata: