version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-test
    environment:
      - MIX_ENV=test
    command: sh -c "mix test test/timemanager_web/controllers/user_controller_test.exs test/timemanager_web/controllers/clock_controller_test.exs"
    volumes:
      - ./backend/test-results:/app/test-results