name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/t-poo-700-nce_10:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/t-poo-700-nce_10:latest

      - name: SSH and deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker pull ${{ secrets.DOCKER_USERNAME }}/t-poo-700-nce_10:latest &&
            docker stop t-poo-700-nce_10 || true &&
            docker rm t-poo-700-nce_10 || true &&
            docker run -d --name t-poo-700-nce_10 -p 80:80 ${{ secrets.DOCKER_USERNAME }}/t-poo-700-nce_10:latest
          '