name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Phoenix image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Build and push Frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "~/"

    - name: Deploy to EC2
      env:
        DOCKER_HOST: ssh://${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }}
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} "mkdir -p ~/.ssh && echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa"
        export DOCKER_HOST=ssh://${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }}
        docker-compose pull
        docker-compose up -d
        rm -f private_key.pem