name: Run Specific Tests
on:
  push:
    branches: [ Test_pipeline, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create test results directory
      run: mkdir -p backend/test-results

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and run tests
      run: |
        docker-compose -f docker-compose.test.yml up --build --exit-code-from backend
      continue-on-error: true

    - name: List test results
      run: |
        echo "Listing test results in backend/test-results:"
        ls -la backend/test-results
        for file in backend/test-results/*.txt; do
          if [ -f "$file" ]; then
            echo "Contents of $file:"
            cat "$file"
          fi
        done

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/test-results

    - name: Check test results
      run: |
        if [ -n "$(find backend/backend/test-results -name '*.txt' -print -quit)" ]; then
          echo "Tests executed and results found."
          exit 0
        else
          echo "No test results found. Tests may have failed to run."
          exit 1
        fi