name: Run Specific Tests

on:
  push:
    branches: [ Test_pipeline, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Disable deprecation warnings
      run: echo "ACTIONS_STEP_DEBUG=false" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache Elixir deps and Node modules
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
          ~/.npm
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock', '**/package-lock.json') }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and test backend
      run: |
        docker build -t backend-test ./backend
        docker run --rm -v ${{ github.workspace }}/backend/test-results:/app/test-results backend-test mix do test test/timemanager_web/controllers/user_controller_test.exs test/timemanager_web/controllers/clock_controller_test.exs

    - name: Run integration tests
      run: |
        docker-compose -f docker-compose.test.yml up --build -d
        docker-compose -f docker-compose.test.yml run -v ${{ github.workspace }}/backend/test-results:/app/test-results backend mix do test test/timemanager_web/controllers/user_controller_test.exs test/timemanager_web/controllers/clock_controller_test.exs
        docker-compose -f docker-compose.test.yml down -v
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/test-results

    - name: Check test results
      if: failure()
      run: exit 1